dist: trusty
sudo: required
language: node_js
node_js:
  - "10"
script:
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update && sudo apt-get install yarn
    - yarn global add electron
    - yarn global add electron-builder
    - yarn install
install:
    - sudo apt-get install rpm
after_success:
    - yarn lint
    - yarn build
    - yarn prod
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
    - "dist/*.zip"
    - "dist/*.deb"
    - "dist/*.rpm"
    - "dist/*.tar.gz"
    - "dist/*.tar.xz"
    - "dist/*.AppImage"
    - "dist/*.pacman"
  skip_cleanup: true
  on:
    tags: true